### PR TITLE
[WIP] Fix MSYS2 build

### PR DESCRIPTION
**Pull request by eustas**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
We should actually try to detect the presence of the `getopt.h` header file.

**Comment by eustas** [comment]
Actually there is double inclusion....

**Comment by eustas** [comment]
Hmm, going to add MSVC build as well...

**Comment by fabiangreffrath** [comment]
> Actually there is double inclusion....

Indeed, line 51. 😆

**Comment by fabiangreffrath** [comment]
> Hmm, going to add MSVC build as well...

Apparently we do not need out local getopt-copy anymore, except maybe for MSVC.

**Pull request merged**
