### PR TITLE
Fix various issues

### PR DESCRIPTION
**Pull request by awesie**
I tried to fix some of the outstanding issues. Please test and double check if you have time.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Wow, thanks!

Could you please elaborate which "outstanding issues" exactly each commit addresses?

**Comment by fabiangreffrath** [comment]
Never mind, I should have read the commit messages!

**Comment by fabiangreffrath** [comment]
I don't have a chance to test all your changes, but they look all reasonable to me. I'll apply them in good faith, thank you very much!

**Comment by fabiangreffrath** [comment]
Since you seem to be knowledgeable of the code and the data format, could you probably have a look at https://github.com/knik0/faad2/commit/466b01d504d7e45f1e9169ac90b3e34ab94aed14 and the linked issues at the mixx bug tracker, please?

**Comment by fabiangreffrath** [comment]
Do you happen to have any more fixes in the line? I'd like to tag the current state as a new release anytime soon but don't want to get in the way if you have more to apply.

**Comment by awesie** [comment]
See #65. There is no rush on it though. It sounds like it #64 is more important to get out in the wild since it fixes a regression.

**Pull request merged**
