### PR TITLE
Visual Studio 2017 projects

### PR DESCRIPTION
**Pull request by vividos**
I updated the project files for libfaad, libfaad2_dll and faad.exe and fixed a syntax error with the NEAACDECAPI macro. More projects to come soon!

### CODE REVIEW

**Comment by knik0** [comment]
OK, but I had to fix the "API" thing for GCC compatibility

**Comment by knik0** [comment]
I just added __declspec( dllimport ) as API type, without it way too many symbols are exported to dll at least with gcc. Could you check how it works with VC?
BTW. is the __cdecl really needed, it's the default and probably can be removed.

**Comment by vividos** [comment]
There are two ways to export functions from shared libraries in Visual Studio, either use a .def file (which faad2 already has), or use __declspec(dllimport) when compiling the library. When actually using the library, the functions must be marked __declspec(dllexport), though. Most encoder projects that I know of use this approach (e.g. LAME, Ogg, libsndfile). I don't know if this works with MINGW gcc, too.

I think there are also two ways to export symbols using gcc: Use the __attribute__((visibility("default"))) to mark functions, or use libtool and a .sym file with similar contents as a .def file. LAME uses this, for example. I don't know exactly how it works.

My suggestion: use the attribute with gcc, and on Visual Studio we use the .def file. The macro VISIBILE could be renamed back to NEAACDECAPI and be placed before the return type. This page sums it up nicely: https://gcc.gnu.org/wiki/Visibility
I will prepare another pull request with changes for Visual Studio.

And: CDECL could be removed, since a big extern "C" scope is aroung the exported functions.

**Comment by knik0** [comment]
MINGW gcc is exporting all global funcs by default but when there is some dllexport only those dllexports are exported so it looks like __declspec(dllexport) has to be used with gcc.

Maybe you could test the recent faac code, I have sanitized the SSE part (quantize.c) and now it's enabled in VC but I'm not really sure if it works well with VC.

**Comment by vividos** [comment]
From reading the https://gcc.gnu.org/wiki/Visibility article I figured that you have to pass -fvisibility=hidden on MinGW, too, to get the same behavior as using dllspec(dllexport).

I'll have a look at faac and the SSE changes!

**Pull request merged**
